export const MODES = {
    POMODORO: 'POMODORO',
    SHORT_BREAK: 'SHORT_BREAK',
    LONG_BREAK: 'LONG_BREAK'
}

export const COLORS = {
    [MODES.POMODORO] : '#DB524D',
    [MODES.SHORT_BREAK] : '#468E91',
    [MODES.LONG_BREAK] : '#437EA8',
}
